
var GlobalConfig={GLOBAL_HINT_SHOWING:3000,INIT_HEIGHT_RATIO:0.30,MIN_EDITOR_HEIGHT:100,MIN_BOARD_HEIGHT:100,OPER_AREA_HEIGHT:25,HSEP_AREA_HEIGHT:25,MISC_HEIGHT:14,VSEP_AREA_HEIGHT:8,RIGHT_FRAME_HEIGHT:141,_nInfoBoardHeight:-1,_nEditorHeight:-1,getEditorHeight:function(){return this._nEditorHeight;},getInfoBoardHeight:function(){return this._nInfoBoardHeight;},setEditorHeight:function(height){height=Math.max(height,this.MIN_EDITOR_HEIGHT);this._nEditorHeight=height;},setInfoBoardHeight:function(height){height=Math.max(height,this.MIN_BOARD_HEIGHT);this._nInfoBoardHeight=height;},getTotalHeight:function(){return(QZONE.dom.getClientHeight()-this.OPER_AREA_HEIGHT-this.HSEP_AREA_HEIGHT-this.MISC_HEIGHT);},getHeightRatio:function(){return this._nEditorHeight/(this._nEditorHeight+this._nInfoBoardHeight);},getLeftSideWidth:function(){return(QZONE.dom.getClientWidth()-this.VSEP_AREA_HEIGHT-this.RIGHT_FRAME_HEIGHT);},init:function(){var totalHeight=this.getTotalHeight();var editorHeight=Math.floor(totalHeight*this.INIT_HEIGHT_RATIO);this.setEditorHeight(editorHeight);this.setInfoBoardHeight(totalHeight-editorHeight);}};var CacheManager={_cacheData:{},_uploadedImg:{},addCacheData:function(key,data){this._cacheData[key]=data;},removeCacheData:function(key){delete this._cacheData[key];this._cacheData[key]=null;},getCacheData:function(key){return this._cacheData[key];},recordUploadedImg:function(oldUrl,newUrl){oldUrl=QZBlog.Util.convertLocalFilePath(oldUrl);this._uploadedImg[oldUrl]=newUrl;},hasImgUploaded:function(oldUrl){oldUrl=QZBlog.Util.convertLocalFilePath(oldUrl);return!!this._uploadedImg[oldUrl];},getImgUploadedUrl:function(oldUrl){oldUrl=QZBlog.Util.convertLocalFilePath(oldUrl);return this._uploadedImg[oldUrl];},initUserData:function(){document.documentElement.addBehavior("#default#userdata");},setUserData:function(key,value){document.documentElement.setAttribute(key,value);document.documentElement.save("miniPortal");},getUserData:function(key){document.documentElement.load("miniPortal");var _v=document.documentElement.getAttribute(key);if(!_v){return"";}else{return _v;}}};var ActionManager={_bSubmitting:false,setPublic:function(npkey,cate,verifycode){var url="http://"+CGI_BLOG_DOMAIN+"/cgi-bin/notepad/notepad_np2blog?uin="+QZBlog.Util.getUin()+"&key="+npkey+"&category="+encodeURIComponent(cate)+
(!!verifycode?("&verifycode="+verifycode+"&verifysession="+QZBlog.Util.getQQCookieValue("verifysession")):"")+"&ref=miniportal"+"&qzoneckey="+QZBlog.Util.getKey()+"&qzonecid="+QZBlog.Util.getClientID();var netProcessor=new QZBlog.Util.BlogNetProcessor();netProcessor.create(url,"post",function(data){var msg=(!!data.tip?data.tip:"成功转换");if(!!msg){QZBlog.Util.showMsgbox(msg,0,QZBlog.Util.MSG_LIFTTIME.HIGH);}
$("notepadTitle_"+npkey).innerHTML='<strong class="notepad_hint_succeed"><span>提示</span></strong>成功转成公开日志';$("setPublicHref_"+npkey).style.display="none";$("viewHref_"+npkey).onclick=function(){QZBlog.Util.openPage("http://user.qzone.qq.com/"+QZBlog.Util.getUin()+"/blog/"+data.blogid);return false;};var arrImgs=$("imgContent_"+npkey).getElementsByTagName("img");for(var index=0;index<arrImgs.length;++index){if(/em\/e(\d{1,3}).gif/i.test(arrImgs[index].src)){continue;}
arrImgs[index].parentNode.onclick=(function(blogid){return function(){QZBlog.Util.openPage("http://user.qzone.qq.com/"+QZBlog.Util.getUin()+"/blog/"+blogid);QZONE.event.preventDefault();};})(data.blogid);}},function(data){QZBlog.Util.showMsgbox(data.error.msg,1,QZBlog.Util.MSG_LIFTTIME.MIDDLE);},"GBK",false);netProcessor.setPostType("externalHTML");netProcessor.loginHandler=function(){QZBlog.Util.hideMsgbox();QZBlog.Util.showAlertDlg("很抱歉，因为网络原因无法发表。请备份好当前的内容，再重新打开QQ空间编辑器尝试。",520);};netProcessor.verifyHandler=QZONE.event.bind(this,function(verifycode){ActionManager.setPublic(npkey,cate,verifycode);});netProcessor.execute();},_getNotePadParam:function(){var ubbContent=PageScheduler.getEditorObj().getContent();if(!PageScheduler.getEditorObj().bFirstFocused||ubbContent.ltrim().length==0){PageScheduler.getEditorObj().procEditorFirstFocused();PageScheduler.getEditorObj().focus();QZONE.widget.bubble.show($("submitBtn"),null,"发表内容不能为空，请重新输入。",{"timeout":1000,"styleText":"width:205px;","xAdjust":-150,"arrowAdjust":110,"noCloseBtn":true});return null;}
if(ubbContent.getRealLength()>MAX_BLOG_LEN){QZBlog.Util.showAlertDlg("您输入的内容长度超出"+(ubbContent.getRealLength()-MAX_BLOG_LEN)+"字节",300,function(){PageScheduler.getEditorObj().focus();});return null;}
var htmlContent=PageScheduler.getEditorObj().getConvertedHTMLContent();var nLen=htmlContent.getRealLength();if(nLen>MAX_BLOG_HTML_LEN){QZBlog.Util.showAlertDlg("您输入的内容长度超出"+(nLen-MAX_BLOG_HTML_LEN)+"字节",300,function(){PageScheduler.getEditorObj().focus();});return null;}
var param={};param["ubbcontent"]=encodeURIComponent(ubbContent);param["htmlcontent"]=encodeURIComponent(htmlContent);param["uin"]=QZBlog.Util.getUin();param["ref"]="miniportal";param["qzoneckey"]=QZBlog.Util.getKey();param["qzonecid"]=QZBlog.Util.getClientID();param["externalImages"]=this._getImageArray(htmlContent);return param;},_getImageArray:function(html){var arr=[];html=html.replace(/<img([^>]+)>/ig,function(){try{var em=/em\/e(\d{1,3}).gif/i.exec(arguments[1]);if(em){return;}
var src=/src="([^"]+)"/i.exec(arguments[1]);if(!!src){if(/^file/gi.test(src[1])){arr.push(src[1]);}}}
catch(err){}
return arguments[0];});return QZONE.lang.uniqueArray(arr);},_replaceImageSrc:function(str,oldSrc,newSrc){var index=-1;while((index=str.indexOf(oldSrc))!=-1){str=str.substr(0,index)+newSrc+str.substr(index+oldSrc.length);}
return str;},_doUploadImages:function(param){$("tipArea").innerHTML="正在发表记事…";mPhoto.uploadFiles(QZONE.lang.objectClone(param["externalImages"]),QZONE.event.bind(this,function(){var htmlContent=decodeURIComponent(param["htmlcontent"]);var ubbContent=decodeURIComponent(param["ubbcontent"]);for(var index=0;index<param["externalImages"].length;++index){var newUrl=CacheManager.getImgUploadedUrl(param["externalImages"][index].toRealStr());if(!newUrl){continue;}
htmlContent=this._replaceImageSrc(htmlContent,param["externalImages"][index],newUrl);ubbContent=this._replaceImageSrc(ubbContent,param["externalImages"][index].toRealStr(),newUrl);}
param["htmlcontent"]=encodeURIComponent(htmlContent);param["ubbcontent"]=encodeURIComponent(ubbContent);delete param["externalImages"];this._submitNotepad(param,true);}),QZONE.event.bind(this,function(errMsg){PageScheduler.getEditorObj().switchEditState();PageScheduler.showFailUploadImgHint(errMsg);$("tipArea").innerHTML="";}));},_uploadImages:function(param){if(!window.g_bPhotoUploadJSLoaded){$("tipArea").innerHTML="正在发表记事…";if(!mPhoto.init()){PageScheduler.getEditorObj().switchEditState();$("tipArea").innerHTML="";return;}
window.g_bPhotoUploadJSLoaded=true;}
this._doUploadImages(param);},_doSubmit:function(param){if(param["externalImages"].length>0){this._uploadImages(param);return;}
this._submitNotepad(param,false);},_submitNotepad:function(param,bUploadImgFlag,verifycode){if(this._bSubmitting){return;}
var url="http://"+CGI_BLOG_DOMAIN+"/cgi-bin/notepad/notepad_add?";for(var key in param){url+=key+"="+param[key]+"&";}
url=url.substr(0,url.length-1);url+=(!!verifycode?("&verifycode="+verifycode+"&verifysession="+QZBlog.Util.getQQCookieValue("verifysession")):"");$("tipArea").innerHTML="正在发表记事…";var netProcessor=new QZBlog.Util.BlogNetProcessor();netProcessor.create(url,"post",QZONE.event.bind(this,function(data){PageScheduler.getEditorObj().switchEditState();$("tipArea").innerHTML="";PageScheduler.getEditorObj().clearContent();DraftLogicManager.setState(false);param["npkey"]=data.key;data.bUploadImgFlag=!!bUploadImgFlag;PageScheduler.showSuccSubmitHint(data);this._bSubmitting=false;}),QZONE.event.bind(this,function(data){this._bSubmitting=false;PageScheduler.getEditorObj().switchEditState();$("tipArea").innerHTML="";var errType=data.error.type;if(errType=="ipc_check"||errType=="verify code"||errType=="verify"||errType=="need_verify"){return;}
if(errType=="notallowed"){PageScheduler.showFailUploadImgHint("你输入的内容可能涉及敏感词汇，请修改后再保存。");return;}
PageScheduler.showFailSubmitHint(param);}),"GBK",true);netProcessor.setPostType("externalHTML");netProcessor.loginHandler=function(){QZBlog.Util.hideMsgbox();QZBlog.Util.showAlertDlg("很抱歉，因为网络原因无法发表。请备份好当前的内容，再重新打开QQ空间编辑器尝试。",520);};netProcessor.verifyHandler=QZONE.event.bind(this,function(verifycode){PageScheduler.getEditorObj().switchEditState();this._submitNotepad(param,bUploadImgFlag,verifycode);});netProcessor.execute();this._bSubmitting=true;},submit:function(){if(!PageScheduler.getEditorObj().getEditorState()){return;}
var param=this._getNotePadParam();if(!param){return;}
PageScheduler.getEditorObj().switchEditState();this._doSubmit(param);},quit:function(bNotCloseFlag){if(DraftLogicManager.getState()){var ubbContent=PageScheduler.getEditorObj().getContent();if(PageScheduler.getEditorObj().bFirstFocused&&ubbContent.length>0){external.QQChangeTab("notepad");QZBlog.Util.popupDialog("温馨提示",'<div><div style="margin:25px 0 0 25px;text-align:center;">记事本尚未保存，关闭会使内容丢失，确定离开吗？</div><div class="mode_pop_bottom mode_pop_bg"><p><button class="spr bt_2" id="quitConfirmBtn" onclick="ActionManager.closeWindow();QZBlog.Util.closePopup();return false;">确定</button><button class="bt_2" onclick="QZBlog.Util.closePopup();return false;">取消</button></p></div></div>',380,110);window.focus();$("quitConfirmBtn").focus();return false;}}
if(!bNotCloseFlag){this.closeWindow();}
return true;},closeWindow:function(){DraftLogicManager.setState(false);external.QQCloseWindow();}};var DraftLogicManager={_bState:false,getState:function(){return this._bState;},setState:function(flag){this._bState=!!flag;},registerDraftTrigger:function(ele,evtName){if(!ele||!evtName){return false;}
return QZONE.event.addEvent(ele,evtName,QZONE.event.bind(this,this.draftStateTrigger));},_beforePageUnloadProc:function(){if(this._bState){return"记事本尚未发表，关闭会使内容丢失，确定离开吗？";}},draftStateTrigger:function(){document.body.onbeforeunload=QZONE.event.bind(this,this._beforePageUnloadProc);this._bState=true;}};var PageScheduler={_oEditorObj:null,getEditorObj:function(){return this._oEditorObj;},_limitHintAreaCnt:function(){if($("displayBoard").childNodes.length<=10){return;}
$("displayBoard").removeChild($("displayBoard").childNodes[0]);},loadGlobalHint:function(){var _jg=new QZFL.JSONGetter("http://imgcache.qq.com/qzone/im/help/announce.json","announce",null,"utf-8");_jg.onSuccess=PageScheduler.showGlobalHint;_jg.onError=function(){}
_jg.send("_Callback");},showGlobalHint:function(o){var _key=o.data+"_"+QZBlog.Util.getUin();if(CacheManager.getUserData(_key)){return;}
CacheManager.setUserData(_key,"1");if(o.hint){$("globalHintText").innerHTML=o.hint;$("globalHint").style.display="";var _tw=new QZFL.Tween($("globalHint"),"opacity",QZFL.transitions.regularEaseInOut,0,1,1);_tw.onMotionStop=function(){PageScheduler._globlaHintTimer=setTimeout(function(){PageScheduler.hideGlobalHint(true);},GlobalConfig.GLOBAL_HINT_SHOWING);}
_tw.start();}},hideGlobalHint:function(blnTween){clearTimeout(PageScheduler._globlaHintTimer);PageScheduler._globlaHintTimer=null;if(!!blnTween){var _tw=new QZFL.Tween($("globalHint"),"opacity",QZFL.transitions.regularEaseInOut,1,0,0.5);_tw.onMotionStop=function(){$("globalHint").style.display="none";}
_tw.start();}else{$("globalHint").style.display="none";}},showSuccSubmitHint:function(serverData){var title="成功发表记事"+(serverData.img.length>0&&!!serverData.bUploadImgFlag?"，图片同时存在您的私密相册中":"");var imgContent="";var reg=new RegExp("em\\/e(\\d{1,3})\.gif","i");for(var index=0;index<serverData.img.length&&index<3;++index){imgContent+='<a target="_blank" href="javascript:;" hidefocus=true onclick="QZBlog.Util.openPage(\'http://user.qzone.qq.com/'+QZBlog.Util.getUin()+'/blog/notepad/'+serverData.key+'\');return false;">'+'<img '+(reg.test(serverData.img[index]["addr"])?'':'width=90 height=90 onload="blogEditorProcImgOnload(this);" alt="图片" ')+'src="'+serverData.img[index]["addr"]+'" /></a>';}
delete reg;var textContent=serverData.abstract;textContent=textContent.replace(/\[em\]e(\d{1,3})\[\/em\]/gi,"<img style='vertical-align:baseline  !important' src='http://imgcache.qq.com/qzone/em/e$1.gif'><wbr>");var strResultHTML=g_succSumbitHint.replace(/<%=title=%>/gi,title).replace(/<%=time=%>/gi,QZBlog.Util.long2DateTime(serverData.pubtime)).replace(/<%=textContent=%>/gi,textContent).replace(/<%=imgContent=%>/gi,imgContent).replace(/<%=npkey=%>/gi,serverData.key).replace(/<%=uin=%>/gi,QZBlog.Util.getUin());var bScroll=false;var oDiv=$("infoBlock_"+serverData.key);if(!oDiv){oDiv=QZONE.dom.createElementIn("div",$("displayBoard"));oDiv.id="infoBlock_"+serverData.key;bScroll=true;}
oDiv.innerHTML=strResultHTML;this._limitHintAreaCnt();if(bScroll){$("displayBoard").scrollTop=$("displayBoard").scrollHeight-$("displayBoard").clientHeight;}},showFailSubmitHint:function(data){if(!data["npkey"]){data["npkey"]="fakekey_"+Math.random();}
var bScroll=false;var oDiv=$("infoBlock_"+data["npkey"]);if(!oDiv){oDiv=QZONE.dom.createElementIn("div",$("displayBoard"));oDiv.id="infoBlock_"+data["npkey"];oDiv.className="notepad_display_hint";bScroll=true;}
oDiv.innerHTML='<p class="diplay_hint_cont"><strong class="notepad_hint_advise"><span>提示</span></strong>很抱歉，您的记事未能发表成功。</p>';this._limitHintAreaCnt();if(bScroll){$("displayBoard").scrollTop=$("displayBoard").scrollHeight-$("displayBoard").clientHeight;}},showFailUploadImgHint:function(msg){var oDiv=QZONE.dom.createElementIn("div",$("displayBoard"));oDiv.className="notepad_display_hint";oDiv.innerHTML='<p class="diplay_hint_cont"><strong class="notepad_hint_advise"><span>提示</span></strong>'+msg+'</p>';this._limitHintAreaCnt();$("displayBoard").scrollTop=$("displayBoard").scrollHeight-$("displayBoard").clientHeight;},resizeLayout:function(){try{var totalHeight=GlobalConfig.getTotalHeight();var tarHeight=Math.floor(totalHeight*GlobalConfig.getHeightRatio());if(!!this._oEditorObj&&this._oEditorObj.bReadyState){if(this._oEditorObj._tipsOpened){var pos=QZONE.dom.getPosition(g_oBlogEditor._dom_tips);tarHeight-=pos["height"]+2;}
this._oEditorObj._dom_area.style.height=tarHeight+"px";this._oEditorObj.resizeArea();}
GlobalConfig.setEditorHeight(tarHeight);GlobalConfig.setInfoBoardHeight(totalHeight-tarHeight);$("displayBoard").style.height=GlobalConfig.getInfoBoardHeight()+"px";var tarWidth=GlobalConfig.getLeftSideWidth();$("displayBoard").parentNode.style.width=(tarWidth-4)+"px";$("rightIframe").style.height=(QZONE.dom.getClientHeight()-6)+"px";}
catch(err){}},buildEditor:function(){$("fakeEditorAnchor").style.display="none";this._oEditorObj=QZONE.editor.create("blogEditorAnchor",{height:"99px"});this._oEditorObj.onEditorReady=QZONE.event.bind(this,function(){this._oEditorObj.bReadyState=true;this._oEditorObj.setHTMLFontSize("12px");this._oEditorObj.setMaxContentLength(MAX_BLOG_HTML_LEN);var editorDoc=this._oEditorObj.getCurrentEditor().getDocument();this.registerSCKey(editorDoc);DraftLogicManager.registerDraftTrigger(editorDoc,"keydown");this._initExternalToolbar();PageScheduler.resizeLayout();this._oEditorObj.bFirstFocused=false;var strTip="写段文字或传张照片，我们将为您保存在QQ空间的记事本或私密相册中，随心记录此刻……";this._oEditorObj.setContentHTML("<div style='color:gray'>"+strTip+"</div>");this._oEditorObj.procEditorFirstFocused=QZONE.event.bind(this,function(){if(!this._oEditorObj.bFirstFocused){this._oEditorObj.clearContent();this._oEditorObj.focus();}
this._oEditorObj.bFirstFocused=true;});QZONE.event.addEvent(editorDoc,"keydown",this._oEditorObj.procEditorFirstFocused);QZONE.event.addEvent(editorDoc,"mousedown",this._oEditorObj.procEditorFirstFocused);this._oEditorObj.procDoubleClick=QZONE.event.bind(this,function(e){var el=QZONE.event.getTarget(e);if(!el){return;}
while(el){if(el.tagName&&el.tagName.toUpperCase()=="IMG"){var isEM=/em\/e(\d{1,3}).gif/i.test(el.src);if(!isEM){var src=el.src;src=QZBlog.Util.convertLocalFilePath(src);external.QQPicDoubleClick(src);return;}}
el=el.parentNode;}});QZONE.event.addEvent(editorDoc,"dblclick",this._oEditorObj.procDoubleClick);QZFL.event.addEvent(this._oEditorObj.getCurrentEditor().getDocument(),"keydown",function(evt){evt=QZONE.event.getEvent(evt);if(evt.ctrlKey&&evt.keyCode==78){QZONE.event.preventDefault(evt);}});});this._oEditorObj.build();},_initExternalToolbar:function(){if(!this._oEditorObj||!this._oEditorObj.bReadyState){return;}
this._emotionPanel=QZFL.widget.emotion.bind($("emotionInsertBtn"));this._emotionPanel.onSelect=QZONE.event.bind(this,function(eObject){if(!PageScheduler.getEditorObj().getEditorState()){return;}
this._oEditorObj.procEditorFirstFocused();this._oEditorObj.focus();this._oEditorObj.getCurrentEditor().fillHtml('<img onresizestart="return false;" src="'+eObject.fileName+'" />');DraftLogicManager.draftStateTrigger();});QZONE.event.addEvent($("imageInsertBtn"),"click",QZONE.event.bind(this,function(){if(!PageScheduler.getEditorObj().getEditorState()){return;}
var filePath=external.QQOpenPic();if(!filePath){return;}
this._oEditorObj.procEditorFirstFocused();this._oEditorObj.focus();this._oEditorObj.getCurrentEditor().fillHtml('<img onresizestart="return false;" class="portal_imgbox_img" onload="parent.blogEditorProcImgOnload(this);" appendurl="1" width=90 height=90 src="'+filePath+'" />');DraftLogicManager.draftStateTrigger();}));QZONE.event.addEvent($("screenImgInsertBtn"),"click",QZONE.event.bind(this,function(){if(!PageScheduler.getEditorObj().getEditorState()){return;}
var filePath=external.QQScreenCut();if(!filePath){return;}
this._oEditorObj.procEditorFirstFocused();this._oEditorObj.focus();this._oEditorObj.getCurrentEditor().fillHtml('<img onresizestart="return false;" class="portal_imgbox_img" onload="parent.blogEditorProcImgOnload(this);" appendurl="1" width=90 height=90 src="'+filePath+'" />');DraftLogicManager.draftStateTrigger();}));},registerSCKey:function(doc){if(!doc){return;}
QZONE.event.addEvent(doc,"keypress",QZFL.event.bind(this,function(evt){evt=QZONE.event.getEvent(evt);if(!!window.bAlertDlgShowFlag){if(evt.keyCode==13){QZBlog.Util.hideAlertDlg();QZONE.event.preventDefault(evt);}
return;}
if(!!window.bPopupDialogFlag){return;}
if(evt.ctrlKey&&evt.keyCode==10){ActionManager.submit();QZONE.event.preventDefault(evt);}
else if(evt.altKey&&evt.keyCode==99){ActionManager.quit();QZONE.event.preventDefault(evt);}}));},bindHTMLEvent:function(){QZONE.event.addEvent(window,"unload",QZONE.event.bind(this,function(){if(!!this._oEditorObj&&this._oEditorObj.bReadyState){var editorDoc=this._oEditorObj.getCurrentEditor().getDocument();QZFL.event.purgeEvent(editorDoc,'keydown');QZFL.event.purgeEvent(editorDoc,'keypress');QZFL.event.purgeEvent(editorDoc,'mousedown');QZFL.event.purgeEvent(editorDoc,'paste');QZFL.event.purgeEvent(editorDoc,'dblclick');}}));QZONE.event.addEvent(window,"resize",QZONE.event.bind(this,this.resizeLayout));QZONE.event.addEvent($("horiToolbar"),"mousedown",DragActionManager.start);QZONE.event.addEvent($("submitBtn"),"click",function(evt){ActionManager.submit();QZONE.event.preventDefault(evt);});QZONE.event.addEvent($("quitBtn"),"click",function(evt){ActionManager.quit();QZONE.event.preventDefault(evt);});this.registerSCKey(document);},start:function(){GlobalConfig.init();CacheManager.initUserData();this.bindHTMLEvent();this.buildEditor();setTimeout(function(){PageScheduler.loadGlobalHint();},2000)}};var DragActionManager={_oDragInfo:null,start:function(evt){var target=QZONE.event.getTarget(evt);if(!target){return;}
document.body.setCapture();DragActionManager._oDragInfo={"object":target,"x":evt.clientX,"y":evt.clientY}
QZONE.event.addEvent(document,"mousemove",DragActionManager.move);QZONE.event.addEvent(document,"mouseup",DragActionManager.end);},move:function(evt){if(!DragActionManager._oDragInfo){DragActionManager.end();return;}
evt=QZONE.event.getEvent(evt);var mY=evt.clientY-DragActionManager._oDragInfo.y;DragActionManager._oDragInfo.y=evt.clientY;var totalHeight=GlobalConfig.getTotalHeight();var boardHeight=GlobalConfig.getInfoBoardHeight()+mY;var editorHeight=GlobalConfig.getEditorHeight()-mY;if(boardHeight<GlobalConfig.MIN_BOARD_HEIGHT||editorHeight<GlobalConfig.MIN_EDITOR_HEIGHT){return;}
GlobalConfig.setInfoBoardHeight(boardHeight);GlobalConfig.setEditorHeight(editorHeight);PageScheduler.resizeLayout();},end:function(evt){DragActionManager._oDragInfo=null;document.body.releaseCapture();QZONE.event.removeEvent(document,"mousemove",DragActionManager.move);QZONE.event.removeEvent(document,"mouseup",DragActionManager.end);}};var g_succSumbitHint=['<div class="notepad_display_hint">','<p class="diplay_hint_cont" id="notepadTitle_<%=npkey=%>"><strong class="notepad_hint_succeed"><span>提示</span></strong><%=title=%></p>','<span class="hint_time"><%=time=%></span>','<div><%=textContent=%></div>','<div class="imgbox" id="imgContent_<%=npkey=%>"><%=imgContent=%></div>','<p class="display_hint_link"><a href="javascript:;" id="viewHref_<%=npkey=%>" onclick="QZBlog.Util.openPage(\'http://user.qzone.qq.com/<%=uin=%>/blog/notepad/<%=npkey=%>\');return false;">查看</a> <a href="javascript:;" id="setPublicHref_<%=npkey=%>" onclick="ActionManager.setPublic(\'<%=npkey=%>\', \'个人日记\');return false;">转成公开日志</a></p>','</div>'].join("");PageScheduler.start();window.resizeEditor=QZONE.event.bind(PageScheduler,PageScheduler.resizeLayout);var mPhoto={init:function(){if(!QPHOTO){return false;}
var nVersion=QPHOTO.widget.upActiveX.getVersion();if(nVersion<224){var strHTML="";if(nVersion==0){strHTML="很抱歉，您当前未安装图片上传控件，记事无法发表成功。<a href='http://imgcache.qq.com/qzone/client/photo/pages/qzone_v4/activex_setup.htm' target='_blank'>点击这里安装</a>";}
else if(nVersion==-1){strHTML="很抱歉，您当前的浏览器不支持图片上传控件，记事无法发表成功。";}
else{strHTML="很抱歉，您当前的图片上传控件版本过低，记事无法发表成功。<a href='http://imgcache.qq.com/qzone/client/photo/pages/qzone_v4/activex_setup.htm' target='_blank'>点击这里升级</a>";}
PageScheduler.showFailUploadImgHint(strHTML);return false;}
mPhoto._uin=QZBlog.Util.getUin();mPhoto._isFamous=0;mPhoto.eleTipArea=$("tipArea");QPHOTO.widget.upActiveX.init({"styleType":2,"options":{"onStartUp":mPhoto.startUp,"onUpResult":mPhoto.upResult,"onUpEndOnce":mPhoto.upEndOnce,"onProgress":mPhoto.progress,"onError":mPhoto.procError}});return true;},procError:function(){mPhoto.errCallback("很抱歉，您的记事图片暂时无法全部上传。");},startUp:function(){mPhoto.errorCnt=0;return mPhoto.setInput();},upResult:function(data,strXML){if(!data.ret){try{var xmlData=QZBlog.Util.parseXML(strXML);var oldUrl=getXMLNodeText(XMLselectSingleNode(xmlData,"/body/Filename")).trim();var newUrl=getXMLNodeText(XMLselectSingleNode(xmlData,"/body/ResultURL")).trim();CacheManager.recordUploadedImg(oldUrl,newUrl);}
catch(err){}}
else{var xmlData=QZBlog.Util.parseXML(strXML);var ret=parseInt(getXMLNodeText(XMLselectSingleNode(xmlData,"/body/Result")).trim(),10);if(ret==-203){mPhoto.nErrorRet=ret;}
if(ret==-202){mPhoto.nErrorRet=ret;}
++mPhoto.errorCnt;}},upEndOnce:function(){if(mPhoto.errorCnt>0){if(mPhoto.nErrorRet==-203){mPhoto.errCallback("很抱歉，记事内的图片名称可能包含敏感字符，请删除后再发表。");}
else if(mPhoto.nErrorRet==-202){mPhoto.errCallback("很抱歉，记事内的图片格式可能有误，请确认是jpg/jepg/png/bmp/gif后再发表。");}
else{mPhoto.procError();}}
else{mPhoto.succCallback();}},progress:function(d){},uploadFiles:function(arrFiles,succCallback,errCallback){if(!arrFiles||!arrFiles.length){return;}
for(var index=0;index<arrFiles.length;++index){arrFiles[index]=arrFiles[index].toRealStr();}
mPhoto.nErrorRet=0;mPhoto.succCallback=(typeof(succCallback)=="function"?succCallback:QZONE.emptyFn);mPhoto.errCallback=(typeof(succCallback)=="function"?errCallback:QZONE.emptyFn);var filterFiles=[];for(var index=0;index<arrFiles.length;++index){if(CacheManager.hasImgUploaded(arrFiles[index])){continue;}
filterFiles.push(QZBlog.Util.convertLocalFilePath(arrFiles[index]));}
if(filterFiles.length==0){mPhoto.succCallback();return;}
mPhoto.totalCnt=filterFiles.length;QPHOTO.widget.upActiveX.setUpFile(filterFiles);this.start();},setInput:function(){var name=mPhoto._isFamous?"pic_up_activex_famous":"pic_up_activex";var url=QPHOTO.url.get({"name":name,"uin":mPhoto._uin,"refer":"qzone"});QPHOTO.widget.upActiveX.setInput({"uin":mPhoto._uin,"aid":"miniportal_notebook","url":url,"name":"","classid":"","priv":"","handset":"","bgid":"","tplid":"","total":0,"extData":{"qzoneckey":QZBlog.Util.getKey(),"qzonecid":QZBlog.Util.getClientID(),"blogtype":7,"refer":"miniportal_notebook"}});return true;},start:function(){PhotoLogic.getExternalUploadUrl({uin:mPhoto._uin,callBack:function(data){setTimeout(QPHOTO.widget.upActiveX.startUp,0);},errBack:function(data){mPhoto.errCallback("很抱歉，获取相册服务器地址失败，您的记事图片暂时无法上传。");}});},stop:function(){QPHOTO.widget.upActiveX.stopUp();}};function QQConfirmClose(){return ActionManager.quit(true);}
function QQDragFile(filePathArrString){if(!PageScheduler.getEditorObj().getEditorState()){return;}
if(!filePathArrString){return;}
filePathArrString=filePathArrString.replace(/\\/g,"/");filePathArrString=eval(filePathArrString);if(!filePathArrString||!filePathArrString.length){return;}
var strHTML="";for(var index=0;index<filePathArrString.length;++index){strHTML+='<img onresizestart="return false;" class="portal_imgbox_img" appendurl="1" onload="parent.blogEditorProcImgOnload(this);" src="'+filePathArrString[index]+'" />';}
window.focus();PageScheduler.getEditorObj().procEditorFirstFocused();PageScheduler.getEditorObj().focus();PageScheduler.getEditorObj().getCurrentEditor().fillHtml(strHTML);DraftLogicManager.draftStateTrigger();}
window.g_strVerifycodeType="notepad";